Fix install fails with Python 2.7
   File "setup.py", line 31, in initialize_options
     super().initialize_options()
 TypeError: super() takes at least 1 argument (0 given)

Python 2 super() requires a type argument and only works for new-style
classes, which setuptools.command.install.install is not.